name: testing

on:
  pull_request:
    branches: ["main"]

jobs:
  lint:
    name: Check the source code
    runs-on: ubuntu-lastest
    steps:
      - useas: actions/checkout@v3
      - name: Install packages
        run: npm i
      - name: Lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          deno-version: "16.17"

      - name: Run Installing dependencies
        run: deno i

      - name: testing our app
        run: npm test

